--- The flashcards, read and changed through the `practice` CLI.
---
--- The Python side owns the card file: where it lives, how it is seeded, how
--- it is saved atomically. Going through the CLI rather than decoding the JSON
--- here means the TUI and the editor can never disagree about any of that.
local config = require("xingshu.config")

local M = {}

---@class xingshu.Card
---@field id string
---@field hanzi string
---@field pinyin string
---@field hsk integer
---@field set integer
---@field starred boolean
---@field learnt boolean

---@param args string[]
---@return string[]
local function command(args)
	return vim.list_extend(vim.deepcopy(config.options.practice_cmd), args)
end

--- A finished CLI run as stdout, or an error message.
---@param cmd string[]
---@param result vim.SystemCompleted
---@return string? stdout, string? err
local function outcome(cmd, result)
	if result.code ~= 0 then
		local err = vim.trim(result.stderr or "")
		if err == "" then
			err = ("`%s` exited %d"):format(cmd[1], result.code)
		end
		return nil, err
	end
	return result.stdout or "", nil
end

---@param cmd string[]
---@return string
local function spawn_error(cmd)
	return ("could not run `%s`"):format(table.concat(cmd, " "))
end

--- Run the `practice` CLI with extra arguments, calling `on_done` on the main loop.
---@param args string[]
---@param on_done fun(stdout: string?, err: string?)
local function run(args, on_done)
	local cmd = command(args)

	-- As in search.query: a missing binary raises instead of calling back.
	local spawned = pcall(vim.system, cmd, { text = true }, function(result)
		vim.schedule(function()
			on_done(outcome(cmd, result))
		end)
	end)

	if not spawned then
		on_done(nil, spawn_error(cmd))
	end
end

--- Run the `practice` CLI and wait for it.
---@param args string[]
---@return string? stdout, string? err
local function run_sync(args)
	local cmd = command(args)
	local spawned, proc = pcall(vim.system, cmd, { text = true })
	if not spawned then
		return nil, spawn_error(cmd)
	end
	return outcome(cmd, proc:wait())
end

--- Load every card.
---@param on_done fun(cards: xingshu.Card[]?, err: string?)
function M.load(on_done)
	run({ "list", "--json" }, function(stdout, err)
		if err then
			on_done(nil, err)
			return
		end
		local ok, cards = pcall(vim.json.decode, stdout)
		if not ok or type(cards) ~= "table" then
			on_done(nil, "`practice list --json` returned something that is not JSON")
			return
		end
		on_done(cards, nil)
	end)
end

--- Cards matching every given filter, in file order.
---@param cards xingshu.Card[]
---@param filter { hsk: integer?, set: integer?, starred: boolean?, learnt: boolean? }
---@return xingshu.Card[]
function M.filter(cards, filter)
	return vim.tbl_filter(function(card)
		return (filter.hsk == nil or card.hsk == filter.hsk)
			and (filter.set == nil or card.set == filter.set)
			and (not filter.starred or card.starred)
			and (not filter.learnt or card.learnt)
	end, cards)
end

--- Cards grouped by set, sets sorted by level then number.
---@param cards xingshu.Card[]
---@return { hsk: integer, set: integer, cards: xingshu.Card[] }[]
function M.sets(cards)
	local by_key = {}
	local sets = {}
	for _, card in ipairs(cards) do
		local key = card.hsk .. "-" .. card.set
		if by_key[key] == nil then
			by_key[key] = { hsk = card.hsk, set = card.set, cards = {} }
			table.insert(sets, by_key[key])
		end
		table.insert(by_key[key].cards, card)
	end
	table.sort(sets, function(a, b)
		if a.hsk ~= b.hsk then
			return a.hsk < b.hsk
		end
		return a.set < b.set
	end)
	return sets
end

--- CLI flag for setting each boolean field.
local flags = {
	starred = { [true] = "--star", [false] = "--unstar" },
	learnt = { [true] = "--learn", [false] = "--unlearn" },
}

--- Set a boolean field of a card and save it.
---
--- `card` is only changed once the CLI has saved, so what is shown never
--- claims something the file does not hold.
---@param card xingshu.Card
---@param field "starred"|"learnt"
---@param value boolean
---@param on_done fun(err: string?)?
function M.set_flag(card, field, value, on_done)
	run({ "edit", card.id, flags[field][value] }, function(_, err)
		if err then
			vim.notify(("xingshu: could not save card %s: %s"):format(card.id, err), vim.log.levels.ERROR)
		else
			card[field] = value
		end
		if on_done then
			on_done(err)
		end
	end)
end

---@class xingshu.CardFields
---@field hanzi string
---@field hsk integer
---@field set integer

--- The card a `--json` add or edit printed.
---@param stdout string?
---@param err string?
---@return xingshu.Card?, string?
local function saved_card(stdout, err)
	if err then
		return nil, err
	end
	local ok, card = pcall(vim.json.decode, stdout)
	if not ok or type(card) ~= "table" then
		return nil, "`practice` printed something that is not a card"
	end
	return card, nil
end

--- Add a card, waiting for it to be saved. Pinyin is generated by the CLI.
---
--- Synchronous so that a buffer write can report failure before `:wq` quits.
---@param fields xingshu.CardFields
---@return xingshu.Card?, string? err
function M.add(fields)
	-- `--` so a sentence starting with a dash is not read as an option.
	return saved_card(run_sync({
		"add",
		"--hsk",
		tostring(fields.hsk),
		"--set",
		tostring(fields.set),
		"--json",
		"--",
		fields.hanzi,
	}))
end

--- Change the fields of `card` that differ from `fields`, waiting for the
--- save. New hanzi gets new pinyin from the CLI. Returns `card` unchanged
--- when there is nothing to do.
---@param card xingshu.Card
---@param fields xingshu.CardFields
---@return xingshu.Card?, string? err
function M.update(card, fields)
	local args = { "edit", card.id, "--json" }
	for _, name in ipairs({ "hanzi", "hsk", "set" }) do
		if fields[name] ~= card[name] then
			-- One `--flag=value` word, so a value starting with a dash is not an option.
			table.insert(args, ("--%s=%s"):format(name, fields[name]))
		end
	end
	if #args == 3 then
		return card, nil
	end
	return saved_card(run_sync(args))
end

--- Delete a card.
---@param card xingshu.Card
---@param on_done fun(err: string?)
function M.remove(card, on_done)
	run({ "rm", card.id }, function(_, err)
		on_done(err)
	end)
end

return M
